"""v4

Revision ID: 20250107_v4
Revises: 20250107_v3
Create Date: 2025-01-07 13:10:47.206242+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250107_v4'
down_revision = '20250107_v3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_vypujcek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kniha_id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=100), nullable=False),
    sa.Column('datum_narozeni', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kniha_id'], ['knihy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_vypujcek')
    # ### end Alembic commands ###
