"""v3

Revision ID: 20250107_v3
Revises: 20241210_v2
Create Date: 2025-01-07 12:57:16.342180+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250107_v3'
down_revision = '20241210_v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knihy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazev', sa.String(length=100), nullable=False),
    sa.Column('iban', sa.String(length=20), nullable=False),
    sa.Column('popisek', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knihy')
    # ### end Alembic commands ###
